//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librarium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class readers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public readers()
        {
            this.fines = new HashSet<fines>();
            this.rentals = new HashSet<rentals>();
        }
    
        public int readerId { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string street { get; set; }
        public string house_no { get; set; }
        public string postal_code { get; set; }
        public string city { get; set; }
        public string voivodeship { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fines> fines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rentals> rentals { get; set; }
    }
}
