//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librarium
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentals
    {
        public int rentalId { get; set; }
        public int readerId { get; set; }
        public int bookId { get; set; }
        public System.DateTime date_of_rent { get; set; }
        public System.DateTime date_of_return { get; set; }
    
        public virtual books books { get; set; }
        public virtual readers readers { get; set; }
    }
}
